---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
        args: ["--branch", "main"]
  - repo: git@github.com:adrienverge/yamllint.git
    rev: v1.20.0
    hooks:
      - id: yamllint
  - repo: git@github.com:nametake/pre-commit-buf.git
    rev: v1.0.0
    hooks:
      - id: buf-check-lint
  - repo: local
    hooks:
      - id: run-golangci-lint
        name: Run golanci-lint
        entry: ./scripts/golangci-lint.sh
        language: script
      - id: run-eslint
        name: Run eslint
        entry: ./scripts/eslint.sh
        language: script
      - id: run-hadolint-server
        name: Run hadolint (server)
        entry: hadolint/hadolint hadolint
        language: docker_image
        files: server/Dockerfile
      - id: run-hadolint-web
        name: Run hadolint (web)
        entry: hadolint/hadolint hadolint
        language: docker_image
        files: web/Dockerfile
