---
run:
  skip-dirs:
    - scripts

output:
  format: colored-line-number
  sort-results: true

linters-settings:
  goimports:
    local-prefixes: github.com/88labs
  maligned:
    suggest-new: true
  wsl:
    allow-cuddle-declarations: true

linters:
  enable-all: true
  disable:
    - gci
    - godox  # 後で有効化する
    - maligned
    - nlreturn
    - paralleltest
    - wsl
